### ISSUE TITLE
deltaLake and HL7

### ISSUE THREAD

**Issue by dridk** [databrickslabs/smolder#11]
Hi, 

Can I feed a deltaLake with HL7 data using smolder ?

**Comment by venkyvb** [comment]
AFAIK this can be done Spark (Scala example below). E.g., something like

```
// Read the raw message
// hl7Path is the path to access the raw incoming hl7 message
val hl7Payload = (spark.read.option("lineSep", "\n\n").text(hl7Path))

// Write to delta table 
// bronzeLakePath is the path to the data lake folder
(hl7Payload.write.format("delta").mode("overwrite").save(bronzeLakePath))

```

**Comment by dridk** [comment]
Thx ! Sorry for my newbe question. I just discovered all the stuff arround deltalake, parquet, spark and so on.

**Comment by venkyvb** [comment]
This example maybe of help - https://github.com/venkyvb/hl7v2spark/blob/main/hl7processing.ipynb
