### ISSUE TITLE
ENH: Recognize and process HL7 messages when MLLP framing bytes are included

### ISSUE THREAD

**Issue by dmoore247** [databrickslabs/smolder#3]
There's a example where the HL7 message is take and placed in a file or on a message queue with the leading `0x0b` and the trailing `0x1c0x0d` byte sequences (the same as found in the MLLP transition).
It would be nice if the parser would recognize the presence of the framing bytes and remove them and parse the message (silent to the end user).

**Comment by ryandecosmo** [comment]
This has been discussed but is not common enough across all users to remove the MLLP envelope automatically. It can be implemented by a user trivially enough before calling the `parse_hl7_message` that we prefer to leave it up to the user for now. If the need grows across the user base this sort of functionality will be considered as a feature addition.
