### ISSUE TITLE
Object functions is not a member of package 

### ISSUE THREAD

**Issue by pfwangs** [databrickslabs/smolder#6]
I am trying to import com.databricks.labs.smolder.functions.parse_hl7_message but I am getting a is not a member error when trying to import in datatricks. I am using Spark 3.2 and Scala 2.12

**Comment by zavoraad** [comment]
Hello, @pfwangs, this package has been updated to be compatible with Spark 3.2. https://github.com/databrickslabs/smolder/releases/tag/v0.0.2
