### ISSUE TITLE
segment returns empty

### ISSUE THREAD

**Issue by utkarsh-ship-it** [databrickslabs/smolder#7]
segment returns empty when parse message with parse_hl7_message function.

Here is the simple scala code:

val message = """MSH|^~\&|||||20201020150800.739+0000||ADT^A03^ADT_A03|11374301|P|2.4
EVN|A03|20170820074419-0500
PID|||d40726da-9b7a-49eb-9eeb-e406708bbb60||Heller^Keneth||||||140 Pacocha Way Suite 52^^Northampton^Massachusetts^^USA
PV1||a|^^^COOLEY DICKINSON HOSPITAL INC THE|ambulatory||||49318f80-bd8b-3fc7-a096-ac43088b0c12^THE^COOLEY||||||||||||||||||||||||||||||||||||20170820074419-0500"""

val columns = Seq("value")
val data = Seq(message)

val rdd = spark.sparkContext.parallelize(data)

val dfFromRDD1 = rdd.toDF()

val parsedDf = dfFromRDD1.select(parse_hl7_message($"value").as("message")) // here we can see that segments return empty
<img width="1428" alt="Screen Shot 2022-01-11 at 5 11 06 AM" src="https://user-images.githubusercontent.com/4970132/148948489-f262693b-8ef0-4776-bc82-30b34530feb3.png">

**Comment by ryandecosmo** [comment]
Hi @utkarsh-ship-it, can you verify if the sample HL7 message you are using has the appropriate newline breaks in it? HL7 segments should be separated by '0x0d' byte character which is an invisible carriage return (as part of the HL7 standard).

I suspect they are not present, so Smolder is seeing the entire message as the MSH segment. (relevant code [here](https://github.com/databrickslabs/smolder/blob/7e5a29a1928a73db1f4a525aca72240662b7228b/src/main/scala/com/databricks/labs/smolder/Message.scala#L68) )

**Comment by utkarsh-ship-it** [comment]
Hi @ryandecosmo  Yes that was the issue. I just fixed it. Sorry my bad. Here I got the clue:   https://github.com/databrickslabs/smolder/blob/7e5a29a1928a73db1f4a525aca72240662b7228b/src/test/scala/com/databricks/labs/smolder/functionsSuite.scala#L33

**Comment by ryandecosmo** [comment]
No problem! Glad you were able to figure it out!

**Comment by utkarsh-ship-it** [comment]
Hi Ryan, do you know if we could use smolder with Apache beam?

Utkarsh
